import { useState, useEffect, useRef } from "react";
import { invoke } from "@tauri-apps/api/core";
import { useGraphStore } from "../../stores/graphStore";
import type { FilePreview } from "../../lib/types";

// Lazy-load Shiki to reduce initial bundle size (~400KB savings)
async function highlight(code: string, lang: string): Promise<string> {
  const { codeToHtml } = await import("shiki");
  return codeToHtml(code, { lang, theme: "vitesse-dark" });
}

interface CodePreviewProps {
  filePath: string;
  language: string;
}

const INITIAL_LINES = 50;
const LOAD_MORE_LINES = 50;

function joinPath(root: string, relative: string): string {
  const trimmed = root.replace(/[/\\]+$/, "");
  return `${trimmed}/${relative}`;
}

export function CodePreview({ filePath, language }: CodePreviewProps) {
  const projectRoot = useGraphStore((s) => s.projectRoot);
  const [html, setHtml] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [visibleLines, setVisibleLines] = useState(INITIAL_LINES);
  const [totalLines, setTotalLines] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);

  const absolutePath = projectRoot ? joinPath(projectRoot, filePath) : filePath;

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setLoading(true);
      setError(null);
      setHtml("");
      setVisibleLines(INITIAL_LINES);

      try {
        const preview = await invoke<FilePreview>("get_file_preview", {
          path: absolutePath,
          maxLines: INITIAL_LINES,
        });

        if (cancelled) return;

        setTotalLines(preview.lineCount);

        const lang = mapLanguage(preview.language || language);
        const highlighted = await highlight(preview.content, lang);

        if (cancelled) return;
        setHtml(highlighted);
      } catch (err) {
        if (cancelled) return;
        const message =
          err instanceof Error ? err.message : "Failed to load file preview";
        setError(message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [absolutePath, language]);

  async function handleShowMore() {
    const nextVisible = visibleLines + LOAD_MORE_LINES;
    try {
      const preview = await invoke<FilePreview>("get_file_preview", {
        path: absolutePath,
        maxLines: nextVisible,
      });

      const lang = mapLanguage(preview.language || language);
      const highlighted = await highlight(preview.content, lang);

      setHtml(highlighted);
      setVisibleLines(nextVisible);
      setTotalLines(preview.lineCount);
    } catch {
      // Existing preview stays visible
    }
  }

  const hasMore = totalLines > visibleLines;

  if (loading) {
    return (
      <div className="flex items-center gap-2 py-4">
        <span className="inline-block h-2 w-2 rounded-full bg-accent-primary animate-pulse-slow" />
        <span className="font-mono text-xs text-text-muted">Loading preview...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded border border-accent-danger/20 bg-accent-danger/5 px-3 py-2 font-mono text-xs text-accent-danger">
        {error}
      </div>
    );
  }

  // dangerouslySetInnerHTML is safe here: HTML is generated by Shiki from local
  // file content fetched via Tauri IPC, and CSP blocks inline script execution.
  return (
    <div className="flex flex-col gap-2">
      <div
        ref={containerRef}
        className="overflow-x-auto rounded border border-border bg-bg-primary text-[11px] leading-relaxed [&_pre]:!bg-transparent [&_pre]:p-3 [&_code]:font-mono"
        dangerouslySetInnerHTML={{ __html: html }}
      />
      {hasMore && (
        <button
          onClick={handleShowMore}
          className="self-start rounded border border-border bg-bg-elevated px-2.5 py-1 font-mono text-[10px] text-text-muted transition-all duration-300 hover:border-accent-primary hover:text-accent-primary"
        >
          Show more ({totalLines - visibleLines} lines remaining)
        </button>
      )}
    </div>
  );
}

/** Map project language names to Shiki language identifiers. */
function mapLanguage(lang: string): string {
  const map: Record<string, string> = {
    typescript: "typescript",
    tsx: "tsx",
    javascript: "javascript",
    jsx: "jsx",
    go: "go",
    rust: "rust",
    python: "python",
    java: "java",
    ruby: "ruby",
    php: "php",
    c: "c",
    cpp: "cpp",
  };
  return map[lang.toLowerCase()] ?? "text";
}
